version: '3'

services:
    postgres:
        image: postgres:12.2
        container_name: skule-vote_postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=skule_vote
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - skule-vote_postgres-data:/var/lib/postgresql/data

volumes:
    skule-vote_postgres-data:
