version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/skule-vote
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300