# Generated by Django 3.2.4 on 2021-08-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="hideable",
        ),
    ]
