# Generated by Django 3.2.2 on 2021-05-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibility',
            name='election',
            field=models.OneToOneField(help_text='Which election do you want to define eligibility for?', on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='backend.election'),
        ),
    ]
