# Generated by Django 3.2.4 on 2021-09-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionsession",
            name="end_time",
            field=models.DateTimeField(
                help_text="When does your Election Session finish? (YYYY-MM-DD and HH:MM:SS)"
            ),
        ),
        migrations.AlterField(
            model_name="electionsession",
            name="start_time",
            field=models.DateTimeField(
                help_text="When does your Election Session start? (YYYY-MM-DD and HH:MM:SS)"
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="hideable",
        ),
    ]
