# Generated by Django 3.2.10 on 2022-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210901_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='student_number_hash',
            field=models.CharField(max_length=64),
        ),
    ]
